name: lm_colosseum
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  equatable:
  responsive_builder:
  flutter_bloc:
  i18n_extension:

flutter:
  uses-material-design: true
